services:
  mysql:
    build: ./database
    ports:
      - "3306:3306"
  config-console:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "443:443"
    environment:
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      OKTA_CLIENT_ID: ${OKTA_CLIENT_ID}
      OKTA_CLIENT_SECRET: ${OKTA_CLIENT_SECRET}
      SHOW_SQL_IN_CONSOLE: ${SHOW_SQL_IN_CONSOLE}
      DATABASE_URL: ${DATABASE_URL}
      IZG_MAX_STATUS_HISTORY_RETURNED: ${IZG_MAX_STATUS_HISTORY_RETURNED}
      IZG_ENDPOINT_CRT_PATH: ${IZG_ENDPOINT_CRT_PATH}
      IZG_ENDPOINT_KEY_PATH: ${IZG_ENDPOINT_KEY_PATH}
      IZG_ENDPOINT_PASSCODE: ${IZG_ENDPOINT_PASSCODE}
      NEXTAUTH_DEBUG: ${NEXTAUTH_DEBUG}
      IZG_STATUS_ENDPOINT_URL: ${IZG_STATUS_ENDPOINT_URL}
      AUTOMATED_TEST_RUN_DURATION: ${AUTOMATED_TEST_RUN_DURATION}
      JIRA_API_URL: ${JIRA_API_URL}
      JIRA_API_AUTH_BASE64: ${JIRA_API_AUTH_BASE64}
      JIRA_API_PROJECT_ID: ${JIRA_API_PROJECT_ID}
      JIRA_API_ISSUE_TYPE: ${JIRA_API_ISSUE_TYPE}
      JIRA_API_ISSUE_DEPLOY_STATE: ${JIRA_API_ISSUE_DEPLOY_STATE}
      JIRA_BROWSER_URL: ${JIRA_BROWSER_URL}
      NEXT_PUBLIC_OKTA_ISSUER: ${NEXT_PUBLIC_OKTA_ISSUER}
      NEXT_PUBLIC_BUILD_ID: ${NEXT_PUBLIC_BUILD_ID}
      NEXT_PUBLIC_GA_ID: ${NEXT_PUBLIC_GA_ID}
      ELASTIC_ENV_TAG: ${ELASTIC_ENV_TAG}
      ELASTIC_HOST: ${ELASTIC_HOST}
      ELASTIC_API_KEY: ${ELASTIC_API_KEY}
      ELASTIC_INDEX: ${ELASTIC_INDEX}
      ELASTIC_INDEX_NGINX: ${ELASTIC_INDEX_NGINX}
      SSL_SOURCE_LOCAL: ${SSL_SOURCE_LOCAL}
      SSL_SOURCE_CONTAINER: ${SSL_SOURCE_CONTAINER}
    volumes:
      - type: bind
        source: ${SSL_SOURCE}
        target: ${SSL_SOURCE}
