---
name: Test, Build and Publish UI Images to Staging

on:
  push:
    branches:
      - main
      - staging
      - production
    paths:
      - 'packages/ui/**'
      - '!/packages/api/**'

env:
  GITHUB_REGISTRY_PREFIX: ghcr.io
  GITHUB_REGISTRY_NAME: izgateway
  IMAGE_NAME: ${{ github.repository }}-ui
  BUILD_ID: ${{ github.run_number}}
  BRANCH: ${{ github.ref_name }}

jobs:
  code-quality-check:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Dynamically set BUILD_RUN_DATETIME environment variable
        run: echo "BUILD_DATETIME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install
        with:
          cache-node-modules: true
      - name: Run UI Jest Tests
        run: yarn workspace @monorepo/ui test
      - name: Lint
        run: yarn lint

  build-and-push-ui-image:
    name: Build and push UI image
    runs-on: ubuntu-latest
    needs: [code-quality-check]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to the GitHub Container registry
        if: ${{ github.ref != 'refs/heads/main' }}
        id: login-ghcr
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.GITHUB_REGISTRY_PREFIX }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to the Amazon ECR
        if: ${{ github.ref == 'refs/heads/main' }}
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.GITHUB_REGISTRY_PREFIX }}/${{ env.IMAGE_NAME }},enable=${{ github.ref != 'refs/heads/main' }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }},enable=${{ github.ref == 'refs/heads/main' }}
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}
            type=raw,value=release,enable=${{ github.ref == 'refs/heads/production' }}
            type=raw,value=snapshot,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=rc,enable=${{ github.ref == 'refs/heads/staging' }}
          flavor: |
            latest=true

      - name: Build and push Docker Config Console ui image
        id: docker_build
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: docker/Dockerfile.ui
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [build-and-push-ui-image]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Staging
        run: echo "Deploy to STAGING code here"
